# Generated by Django 3.1.7 on 2021-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210731_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
    ]
