# Generated by Django 3.1.7 on 2021-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_warehouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
